### ISSUE TITLE
more parameters for search

### ISSUE THREAD

**Issue by anupamme** [onlinetravelgroup/ean-client#3]
Hello,

I need to set following params while doing ean search:

1. show_sold_out = true
2. number_of_results = 200 (or some large number).

How do I set?

**Comment by ryanhughes** [comment]
Hey

I'm not aware of any way to get the EAN API to return sold out results but you can include them by using the `hotelIdList` parameter and merging the API result back in with the hotel list. To use hotelIdList you would first run a search against a local database for the hotel ids. EAN have some scripts for maintaining a local hotel database here https://github.com/ExpediaInc/ean-pc-dbscripts

For the second question the parameter to use is [numberOfResults](http://developer.ean.com/docs/hotel-list#numberOfResults). The maximum amount EAN will return per page is 200, to get more the result has to be paged using cacheKey and cacheLocation.
